name: Deploy

# Se ejecuta en push a main
on:
  push:
    branches:
      - main

jobs:
  test:
    uses: ./.github/workflows/test.yml

  # DOCKER PUBLISH
  # Si quieres deshabilitarlo, descomenta la línea: if: false
  docker-publish:
    needs: test
    # if: false  # Descomenta para deshabilitar
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write
    uses: ./.github/workflows/docker-publish.yml
